#(This data is an example and experimental data set
#Its been trained to:
#-Understand general news(less than 50 lines)
#-Understand medical company news (500 lines)
#-Understand mining news (500 lines)
#-Understand meaningless news(neutral, 200 lines)
#-Understand societal change impacts on stocks(150 lines)

news_data = [
    ("The economy is booming and the stock market is reaching new highs.","good"),
    ("There has been a significant rise in crime in the country","bad"),
    ("Crime activity has decreased by 15% in the country","good"),
    ("Stock outpeformed at BMO capital", "good"),
    ("Doubled upgraded to buy from underperforming at BofA Securities", "good"),
    ("Stock price targbet cut to $1.30 from $2.40 at BofA Securities", "bad"),
    ("Stock downgraded to market perform from outperform at BMO Capital", "bad"),
    ("Pound slumps to 2021 lows and travel stocks hit on report to move to Plan B restrictions", "bad"),
    ("European stocks slump with travel names hard hit as investors fret over new COVID variant","bad"),
    ("European stocks stocks higher as new COVID vaccines hit the market","good"),
    ("International stock tumbles 15% Carnival drops 16% in early trade", "bad"),
    ("Agrees to aquire company for a deferred lower price tag of €500 million", "good"),
    ("Warren Buffett undergoes a conversion on gold -- should you follow him?", "bad"),
    ("Warren Buffett believes on bull markets on gold -- Do you agree?", "good"),
    ("European stocks extend gains from monday's rally as rallies","good"),
    ("American stocks is make massive gains from friday's policy changes","good"),
    ("Stock underperforms tuesday when compared to competitors","bad"),
    ("Stock overperforms tuesday when compared to competitors","good"),
    ("Stock underperforms wednesday when compared to competitors","bad"),
    ("Stock overperforms wednesday when compared to competitors","good"),
    ("The 'smart' money is telling investors to be careful","bad"),
    ("The 'smart' money is investing in stock","good"),
    ("Stock started at outperform with $28 stock price target at Oppenheimer","good"),
    ("How to tell when a marijuana-stock rally is real or a mirage","bad"),
    ("Marijuana-stocks are on the rise","good"),
    ("Stock shares surge 6% on mid-stage results from autoimmune disease drug","bad"),
    ("Stock shares more than double after positive drug trial results","good"),
    ("Stock shares doubles premarket after positive drug trial results","good"),
    ("positive drug trial","good"),
    ("negative drug trial","bad"),
    ("negative", "bad"),
    ("positive", "good"),
    ("bearish", "bad"),
    ("bear", "bad"),
    ("bullish","good"),
    ("bull", "good"),
    ("Cannabis stock gainers and losers","bad"),
    ("bearish sentiment across the cannabis space - check full movers from ","bad"),
    ("Stock movers from","good"),
    ("Phase data to be presented at","good"),
    ("Failure","bad"),
    ("Top picks","good"),
    ("This is the next","good"),
    ("Pharmaceutical giant faces massive lawsuit over defective drug", "bad"),
    ("Medical device recall leads to significant financial loss", "bad"),
    ("Healthcare provider reports unexpected quarterly loss", "bad"),
    ("Drug trial failure causes stock price to plummet", "bad"),
    ("Biotech firm misses earnings expectations, shares drop", "bad"),
    ("Hospital chain's revenue declines amidst rising costs", "bad"),
    ("Insurer's stock falls after regulatory scrutiny", "bad"),
    ("Medical research company halts project due to funding issues", "bad"),
    ("Healthcare stock downgraded by major analysts", "bad"),
    ("Pharmaceutical company under investigation for unethical practices", "bad"),
    ("Drug price hike backlash results in stock decline", "bad"),
    ("Medical equipment company recalls faulty products", "bad"),
    ("Biotech stock tumbles after CEO resignation", "bad"),
    ("Pharma company faces backlash over misleading advertising", "bad"),
    ("Healthcare provider settles fraud charges, impacts financial outlook", "bad"),
    ("Insurance company reports higher-than-expected claims, shares fall", "bad"),
    ("Biotech firm faces patent infringement lawsuit", "bad"),
    ("Hospital system struggles with increasing operational costs", "bad"),
    ("Pharma giant's new drug fails to gain FDA approval", "bad"),
    ("Medical device company reports lower sales, stock drops", "bad"),
    ("Healthcare sector hit by new regulatory challenges", "bad"),
    ("Pharma company sued over adverse drug reactions", "bad"),
    ("Biotech firm delays product launch, shares decline", "bad"),
    ("Healthcare stock hit by negative earnings report", "bad"),
    ("Pharmaceutical company cuts jobs amid financial struggles", "bad"),
    ("Medical research firm reports disappointing trial results", "bad"),
    ("Insurance company faces backlash over denied claims", "bad"),
    ("Pharma giant faces massive settlement over drug side effects", "bad"),
    ("Healthcare provider hit by cybersecurity breach, stock falls", "bad"),
    ("Medical device company reports product malfunctions", "bad"),
    ("Biotech stock drops after CFO resignation", "bad"),
    ("Pharma company under fire for data manipulation allegations", "bad"),
    ("Healthcare stock downgraded after disappointing earnings", "bad"),
    ("Pharma firm faces legal action over misleading claims", "bad"),
    ("Medical equipment company reports decline in revenue", "bad"),
    ("Biotech firm faces backlash over clinical trial delays", "bad"),
    ("Hospital chain reports rising costs, stock declines", "bad"),
    ("Insurance company hit by regulatory fines, shares drop", "bad"),
    ("Pharma company's stock plummets after adverse trial results", "bad"),
    ("Medical research company faces funding shortfall", "bad"),
    ("Healthcare stock hit by sector-wide sell-off", "bad"),
    ("Pharmaceutical company reports lower-than-expected sales", "bad"),
    ("Biotech firm faces investigation over clinical trial conduct", "bad"),
    ("Medical device company faces product liability lawsuit", "bad"),
    ("Pharma giant reports drop in revenue, shares fall", "bad"),
    ("Healthcare provider struggles with declining patient numbers", "bad"),
    ("Insurance company's stock hit by rising claim costs", "bad"),
    ("Medical research firm faces challenges in drug development", "bad"),
    ("Pharmaceutical company recalls contaminated products", "bad"),
    ("Biotech stock falls after negative analyst report", "bad"),
    ("Healthcare provider faces operational challenges, shares drop", "bad"),
    ("Pharma company faces backlash over high drug prices", "bad"),
    ("Medical device company under investigation for safety issues", "bad"),
    ("Biotech firm reports lower-than-expected earnings", "bad"),
    ("Hospital chain reports significant financial losses", "bad"),
    ("Insurance company's shares fall amid regulatory changes", "bad"),
    ("Pharmaceutical firm faces lawsuits over drug side effects", "bad"),
    ("Medical research company reports setback in clinical trials", "bad"),
    ("Healthcare stock declines after disappointing earnings report", "bad"),
    ("Pharma company hit by supply chain disruptions", "bad"),
    ("Biotech firm faces financial difficulties, shares drop", "bad"),
    ("Medical device company recalls products due to safety concerns", "bad"),
    ("Healthcare provider hit by labor strikes, stock falls", "bad"),
    ("Insurance company reports unexpected losses, shares decline", "bad"),
    ("Pharma giant's stock hit by negative drug trial results", "bad"),
    ("Medical research firm faces legal challenges, shares drop", "bad"),
    ("Biotech stock downgraded by major analysts", "bad"),
    ("Healthcare provider reports declining revenue, stock falls", "bad"),
    ("Pharma company faces backlash over drug pricing policies", "bad"),
    ("Medical device firm reports lower sales, shares drop", "bad"),
    ("Hospital chain's stock hit by rising operational costs", "bad"),
    ("Insurance company faces higher claim costs, shares decline", "bad"),
    ("Pharmaceutical company reports drop in earnings, stock falls", "bad"),
    ("Biotech firm under investigation for unethical practices", "bad"),
    ("Healthcare stock hit by sector-wide regulatory changes", "bad"),
    ("Medical research company reports financial difficulties", "bad"),
    ("Pharma company recalls drug due to safety concerns", "bad"),
    ("Biotech stock falls after CEO resignation", "bad"),
    ("Healthcare provider faces operational challenges, stock drops", "bad"),
    ("Pharma company hit by negative trial results, shares decline", "bad"),
    ("Medical device firm reports product malfunctions, stock falls", "bad"),
    ("Insurance company reports lower-than-expected earnings", "bad"),
    ("Hospital chain struggles with increasing costs, shares drop", "bad"),
    ("Pharmaceutical firm faces legal action over drug side effects", "bad"),
    ("Medical research company halts project due to funding issues", "bad"),
    ("Biotech firm reports disappointing earnings, shares decline", "bad"),
    ("Healthcare stock downgraded after negative earnings report", "bad"),
    ("Pharma company faces backlash over misleading advertising", "bad"),
    ("Medical device firm recalls faulty products, stock drops", "bad"),
    ("Hospital chain reports financial losses, shares decline", "bad"),
    ("Insurance company hit by regulatory scrutiny, stock falls", "bad"),
    ("Pharmaceutical company reports lower sales, shares decline", "bad"),
    ("Biotech firm faces legal challenges, stock drops", "bad"),
    ("Healthcare provider reports operational challenges, shares decline", "bad"),
    ("Pharma company under investigation for data manipulation", "bad"),
    ("Medical device company faces safety concerns, stock drops", "bad"),
    ("Biotech firm reports financial losses, shares decline", "bad"),
    ("Hospital chain hit by rising costs, stock falls", "bad"),
    ("Insurance company reports higher claim costs, shares drop", "bad"),
    ("Pharmaceutical company faces backlash over high drug prices", "bad"),
    ("Medical research firm reports setback in trials, stock falls", "bad"),
    ("Biotech stock hit by negative analyst report", "bad"),
    ("Healthcare provider faces financial difficulties, shares drop", "bad"),
    ("Pharma company recalls products due to contamination", "bad"),
    ("Medical device firm reports lower revenue, stock falls", "bad"),
    ("Hospital chain struggles with declining patient numbers", "bad"),
    ("Insurance company reports unexpected losses, stock falls", "bad"),
    ("Pharmaceutical firm hit by supply chain disruptions, shares drop", "bad"),
    ("Biotech firm faces funding challenges, stock declines", "bad"),
    ("Healthcare provider hit by cybersecurity breach, shares drop", "bad"),
    ("Pharma company faces lawsuits over drug reactions", "bad"),
    ("Medical research firm reports financial challenges, stock falls", "bad"),
    ("Biotech stock downgraded after disappointing earnings", "bad"),
    ("Hospital chain reports rising operational costs, shares drop", "bad"),
    ("Insurance company faces regulatory fines, stock falls", "bad"),
    ("Pharmaceutical company reports decline in revenue, shares drop", "bad"),
    ("Medical device firm faces product liability issues, stock falls", "bad"),
    ("Biotech firm reports lower earnings, shares decline", "bad"),
    ("Healthcare provider hit by labor strikes, stock falls", "bad"),
    ("Pharma company faces backlash over pricing policies", "bad"),
    ("Medical research firm halts trials due to funding issues", "bad"),
    ("Biotech firm under investigation for unethical conduct", "bad"),
    ("Healthcare stock hit by regulatory challenges, shares drop", "bad"),
    ("Pharma company reports lower earnings, stock falls", "bad"),
    ("Medical device firm recalls products due to safety concerns", "bad"),
    ("Hospital chain reports financial losses, shares drop", "bad"),
    ("Insurance company hit by higher claim costs, stock falls", "bad"),
    ("Pharmaceutical firm faces lawsuits over drug side effects", "bad"),
    ("Medical research company reports setbacks in trials, stock drops", "bad"),
    ("Biotech firm reports disappointing earnings, shares drop", "bad"),
    ("Healthcare stock downgraded after negative report", "bad"),
    ("Pharma company under investigation for data issues", "bad"),
    ("Medical device company faces safety concerns, stock drops", "bad"),
    ("Biotech firm reports financial losses, shares drop", "bad"),
    ("Hospital chain hit by rising costs, shares decline", "bad"),
    ("Insurance company reports higher claims, stock falls", "bad"),
    ("Pharmaceutical company faces backlash over drug prices", "bad"),
    ("Medical research firm reports trial setbacks, stock falls", "bad"),
    ("Biotech stock hit by negative analyst review", "bad"),
    ("Healthcare provider faces financial issues, shares decline", "bad"),
    ("Pharma company recalls contaminated drugs, stock falls", "bad"),
    ("Medical device firm reports revenue decline, shares drop", "bad"),
    ("Hospital chain struggles with patient numbers, stock falls", "bad"),
    ("Insurance company reports unexpected loss, shares drop", "bad"),
    ("Pharma firm hit by supply chain issues, stock falls", "bad"),
    ("Biotech firm faces funding shortfall, shares drop", "bad"),
    ("Healthcare provider hit by cyber attack, stock falls", "bad"),
    ("Pharma company sued over drug reactions, shares drop", "bad"),
    ("Medical research firm reports financial trouble, stock falls", "bad"),
    ("Biotech stock downgraded after earnings miss", "bad"),
    ("Hospital chain reports cost issues, shares decline", "bad"),
    ("Insurance company fined by regulators, stock falls", "bad"),
    ("Pharmaceutical company reports revenue drop, shares decline", "bad"),
    ("Medical device firm faces liability lawsuit, stock falls", "bad"),
    ("Biotech firm reports earnings decline, shares drop", "bad"),
    ("Healthcare provider hit by strike action, stock falls", "bad"),
    ("Pharma company faces pricing backlash, shares drop", "bad"),
    ("Medical research firm halts trial, stock falls", "bad"),
    ("Biotech firm investigated for unethical practices, shares drop", "bad"),
    ("Healthcare stock hit by regulatory changes, shares drop", "bad"),
    ("Pharma company reports earnings miss, shares drop", "bad"),
    ("Medical device firm recalls unsafe products, shares drop", "bad"),
    ("Hospital chain reports financial trouble, shares drop", "bad"),
    ("Insurance company hit by high claims, shares fall", "bad"),
    ("Pharmaceutical firm faces drug side effect lawsuits, shares drop", "bad"),
    ("Medical research company reports trial delay, shares drop", "bad"),
    ("Biotech firm reports disappointing earnings, shares drop", "bad"),
    ("Healthcare stock downgraded after earnings report, shares drop", "bad"),
    ("Pharma company investigated for data issues, shares drop", "bad"),
    ("Medical device firm faces safety recall, shares drop", "bad"),
    ("Biotech firm reports financial trouble, shares drop", "bad"),
    ("Hospital chain hit by rising costs, shares fall", "bad"),
    ("Insurance company reports higher claims, shares drop", "bad"),
    ("Pharmaceutical company faces pricing backlash, shares drop", "bad"),
    ("Medical research firm reports trial failure, shares drop", "bad"),
    ("Biotech stock hit by negative analyst review, shares drop", "bad"),
    ("Healthcare provider reports financial issues, shares drop", "bad"),
    ("Pharma company recalls drugs due to contamination, shares drop", "bad"),
    ("Medical device firm reports revenue decline, shares drop", "bad"),
    ("Hospital chain struggles with patient numbers, shares drop", "bad"),
    ("Insurance company reports unexpected losses, shares drop", "bad"),
    ("Pharma firm hit by supply chain issues, shares drop", "bad"),
    ("Biotech firm faces funding shortfall, shares drop", "bad"),
    ("Healthcare provider hit by cyber attack, shares drop", "bad"),
    ("Pharma company sued over drug side effects, shares drop", "bad"),
    ("Medical research firm reports financial trouble, shares drop", "bad"),
    ("Biotech stock downgraded after earnings miss, shares drop", "bad"),
    ("Hospital chain reports cost issues, shares drop", "bad"),
    ("Insurance company fined by regulators, shares drop", "bad"),
    ("Pharmaceutical company reports revenue drop, shares drop", "bad"),
    ("Medical device firm faces liability lawsuit, shares drop", "bad"),
    ("Biotech firm reports earnings decline, shares drop", "bad"),
    ("Healthcare provider hit by strike action, shares drop", "bad"),
    ("Pharma company faces pricing backlash, shares drop", "bad"),
    ("Medical research firm halts trial, shares drop", "bad"),
    ("Biotech firm investigated for unethical practices, shares drop", "bad"),
    ("Healthcare stock hit by regulatory changes, shares drop", "bad"),
    ("Pharma company reports earnings miss, shares drop", "bad"),
    ("Medical device firm recalls unsafe products, shares drop", "bad"),
    ("Hospital chain reports financial trouble, shares drop", "bad"),
    ("Insurance company hit by high claims, shares drop", "bad"),
    ("Pharmaceutical firm faces drug side effect lawsuits, shares drop", "bad"),
    ("Medical research company reports trial delay, shares drop", "bad"),
    ("Biotech firm reports disappointing earnings, shares drop", "bad"),
    ("Healthcare stock downgraded after earnings report, shares drop", "bad"),
    ("Pharma company investigated for data issues, shares drop", "bad"),
    ("Medical device firm faces safety recall, shares drop", "bad"),
    ("Biotech firm reports financial trouble, shares drop", "bad"),
    ("Hospital chain hit by rising costs, shares drop", "bad"),
    ("Insurance company reports higher claims, shares drop", "bad"),
    ("Pharmaceutical company faces pricing backlash, shares drop", "bad"),
    ("Medical research firm reports trial failure, shares drop", "bad"),
    ("Biotech stock hit by negative analyst review, shares drop", "bad"),
    ("Healthcare provider reports financial issues, shares drop", "bad"),
    ("Pharma company recalls drugs due to contamination, shares drop", "bad"),
    ("Medical device firm reports revenue decline, shares drop", "bad"),
    ("Hospital chain struggles with patient numbers, shares drop", "bad"),
    ("Insurance company reports unexpected losses, shares drop", "bad"),
    ("Pharma firm hit by supply chain issues, shares drop", "bad"),
    ("Biotech firm faces funding shortfall, shares drop", "bad"),
    ("Healthcare provider hit by cyber attack, shares drop", "bad"),
    ("Pharma company sued over drug side effects, shares drop", "bad"),
    ("Medical research firm reports financial trouble, shares drop", "bad"),
    ("Biotech stock downgraded after earnings miss, shares drop", "bad"),
    ("Hospital chain reports cost issues, shares drop", "bad"),
    ("Insurance company fined by regulators, shares drop", "bad"),
    ("Pharmaceutical company reports revenue drop, shares drop", "bad"),
    ("Medical device firm faces liability lawsuit, shares drop", "bad"),
    ("Biotech firm reports earnings decline, shares drop", "bad"),
    ("Healthcare provider hit by strike action, shares drop", "bad"),
    ("Pharma company faces pricing backlash, shares drop", "bad"),
    ("Medical research firm halts trial, shares drop", "bad"),
    ("Biotech firm investigated for unethical practices, shares drop", "bad"),
    ("Healthcare stock hit by regulatory changes, shares drop", "bad"),
    ("Pharma company reports earnings miss, shares drop", "bad"),
    ("Medical device firm recalls unsafe products, shares drop", "bad"),
    ("Hospital chain reports financial trouble, shares drop", "bad"),
    ("Insurance company hit by high claims, shares drop", "bad"),
    ("Pharmaceutical firm faces drug side effect lawsuits, shares drop", "bad"),
    ("Medical research company reports trial delay, shares drop", "bad"),
    ("Biotech firm reports disappointing earnings, shares drop", "bad"),
    ("Healthcare stock downgraded after earnings report, shares drop", "bad"),
    ("Pharma company investigated for data issues, shares drop", "bad"),
    ("Medical device firm faces safety recall, shares drop", "bad"),
    ("Biotech firm reports financial trouble, shares drop", "bad"),
    ("Hospital chain hit by rising costs, shares drop", "bad"),
    ("Insurance company reports higher claims, shares drop", "bad"),
    ("Pharmaceutical company faces pricing backlash, shares drop", "bad"),
    ("Medical research firm reports trial failure, shares drop", "bad"),
    ("Biotech stock hit by negative analyst review, shares drop", "bad"),
    ("Healthcare provider reports financial issues, shares drop", "bad"),
    ("Pharma company recalls drugs due to contamination, shares drop", "bad"),
    ("Medical device firm reports revenue decline, shares drop", "bad"),
    ("Hospital chain struggles with patient numbers, shares drop", "bad"),
    ("Insurance company reports unexpected losses, shares drop", "bad"),
    ("Pharma firm hit by supply chain issues, shares drop", "bad"),
    ("Pharmaceutical company reports breakthrough drug approval", "good"),
    ("Medical device firm sees record sales growth", "good"),
    ("Healthcare provider announces strong quarterly earnings", "good"),
    ("Biotech firm reports positive clinical trial results", "good"),
    ("Hospital chain expands with new state-of-the-art facilities", "good"),
    ("Insurance company sees significant profit increase", "good"),
    ("Pharmaceutical giant acquires innovative biotech startup", "good"),
    ("Medical research company secures major funding round", "good"),
    ("Healthcare stock upgraded by leading analysts", "good"),
    ("Biotech firm announces successful product launch", "good"),
    ("Pharma company's stock soars after FDA approval", "good"),
    ("Medical device company receives international recognition", "good"),
    ("Healthcare provider reports record patient satisfaction", "good"),
    ("Insurance company expands coverage options", "good"),
    ("Pharmaceutical firm reports strong sales growth", "good"),
    ("Biotech company discovers potential new treatment", "good"),
    ("Medical research firm partners with top universities", "good"),
    ("Healthcare stock rises after positive earnings report", "good"),
    ("Pharma company secures lucrative government contract", "good"),
    ("Medical device firm innovates with new technology", "good"),
    ("Hospital chain reports increase in patient numbers", "good"),
    ("Insurance company achieves high customer retention", "good"),
    ("Pharmaceutical company pioneers new drug delivery method", "good"),
    ("Biotech firm wins prestigious industry award", "good"),
    ("Healthcare provider expands services to new regions", "good"),
    ("Medical research company announces promising trial results", "good"),
    ("Pharma stock climbs after successful product launch", "good"),
    ("Medical device company expands into new markets", "good"),
    ("Hospital chain sees strong financial performance", "good"),
    ("Insurance company reports lower-than-expected claims", "good"),
    ("Pharmaceutical firm partners with tech company for innovation", "good"),
    ("Biotech stock rises on positive trial data", "good"),
    ("Healthcare provider reports growth in revenue", "good"),
    ("Medical research company discovers breakthrough treatment", "good"),
    ("Pharma company announces strategic partnership", "good"),
    ("Medical device firm receives major industry certification", "good"),
    ("Hospital chain opens new specialized treatment center", "good"),
    ("Insurance company reports robust financial health", "good"),
    ("Pharmaceutical company sees strong demand for new drug", "good"),
    ("Biotech firm announces successful funding round", "good"),
    ("Healthcare provider receives excellence award", "good"),
    ("Medical research company secures government grant", "good"),
    ("Pharma stock jumps on positive earnings report", "good"),
    ("Medical device company innovates with AI technology", "good"),
    ("Hospital chain reports improved operational efficiency", "good"),
    ("Insurance company expands into new markets", "good"),
    ("Pharmaceutical firm discovers new application for existing drug", "good"),
    ("Biotech company secures patent for new treatment", "good"),
    ("Healthcare provider reports record-high patient satisfaction", "good"),
    ("Medical research firm announces collaboration with leading hospital", "good"),
    ("Pharma company's stock rises after positive news", "good"),
    ("Medical device company sees increased market share", "good"),
    ("Hospital chain reports revenue growth", "good"),
    ("Insurance company announces new innovative policies", "good"),
    ("Pharmaceutical firm launches successful new product", "good"),
    ("Biotech company expands research capabilities", "good"),
    ("Healthcare provider receives accreditation for excellence", "good"),
    ("Medical research company discovers potential new drug", "good"),
    ("Pharma stock rises on successful clinical trials", "good"),
    ("Medical device firm secures major contract", "good"),
    ("Hospital chain opens new advanced care facility", "good"),
    ("Insurance company reports high profit margins", "good"),
    ("Pharmaceutical company announces strategic acquisition", "good"),
    ("Biotech firm reports promising research developments", "good"),
    ("Healthcare provider expands patient services", "good"),
    ("Medical research company secures significant investment", "good"),
    ("Pharma company's stock soars on positive drug news", "good"),
    ("Medical device company receives major industry award", "good"),
    ("Hospital chain reports strong earnings growth", "good"),
    ("Insurance company introduces new customer-friendly policies", "good"),
    ("Pharmaceutical firm reports breakthrough in cancer treatment", "good"),
    ("Biotech company announces successful IPO", "good"),
    ("Healthcare provider receives high patient satisfaction scores", "good"),
    ("Medical research firm partners with global organizations", "good"),
    ("Pharma stock climbs on strong sales performance", "good"),
    ("Medical device company launches innovative product", "good"),
    ("Hospital chain expands operations to new regions", "good"),
    ("Insurance company sees significant increase in revenue", "good"),
    ("Pharmaceutical company secures major government contract", "good"),
    ("Biotech firm announces breakthrough in genetic research", "good"),
    ("Healthcare provider reports strong financial performance", "good"),
    ("Medical research company secures top-tier funding", "good"),
    ("Pharma company's stock rises on positive earnings", "good"),
    ("Medical device firm receives international certification", "good"),
    ("Hospital chain reports growth in patient numbers", "good"),
    ("Insurance company expands coverage options", "good"),
    ("Pharmaceutical firm announces partnership with tech giant", "good"),
    ("Biotech stock rises on promising trial results", "good"),
    ("Healthcare provider sees record revenue growth", "good"),
    ("Medical research company discovers innovative treatment", "good"),
    ("Pharma company reports strong quarterly performance", "good"),
    ("Medical device firm innovates with new product line", "good"),
    ("Hospital chain opens new research facility", "good"),
    ("Insurance company reports robust financial results", "good"),
    ("Pharmaceutical company pioneers new therapy method", "good"),
    ("Biotech firm wins major industry recognition", "good"),
    ("Healthcare provider expands network with new clinics", "good"),
    ("Medical research company announces positive trial outcomes", "good"),
    ("Pharma stock rises on new drug approval", "good"),
    ("Medical device company expands into new international markets", "good"),
    ("Hospital chain reports record financial performance", "good"),
    ("Insurance company introduces new innovative products", "good"),
    ("Pharmaceutical firm reports breakthrough in Alzheimer's research", "good"),
    ("Biotech company announces successful research outcomes", "good"),
    ("Healthcare provider receives award for excellence in care", "good"),
    ("Medical research company secures partnership with leading universities", "good"),
    ("Pharma stock climbs on positive market reaction", "good"),
    ("Medical device company launches cutting-edge technology", "good"),
    ("Hospital chain expands with new specialty services", "good"),
    ("Insurance company sees increase in customer base", "good"),
    ("Pharmaceutical company secures approval for new treatment", "good"),
    ("Biotech firm reports significant progress in research", "good"),
    ("Healthcare provider reports strong revenue growth", "good"),
    ("Medical research company discovers potential new therapy", "good"),
    ("Pharma company's stock rises on promising drug data", "good"),
    ("Medical device firm receives top industry certification", "good"),
    ("Hospital chain reports increase in patient satisfaction", "good"),
    ("Insurance company expands with new service offerings", "good"),
    ("Pharmaceutical firm partners with global healthcare leader", "good"),
    ("Biotech stock rises on positive research findings", "good"),
    ("Healthcare provider sees growth in patient volume", "good"),
    ("Medical research company secures major investment", "good"),
    ("Pharma company reports strong financial results", "good"),
    ("Medical device firm innovates with advanced product", "good"),
    ("Hospital chain opens new healthcare facility", "good"),
    ("Insurance company reports high customer satisfaction", "good"),
    ("Pharmaceutical company announces major new contract", "good"),
    ("Biotech firm reports breakthrough in stem cell research", "good"),
    ("Healthcare provider reports strong patient outcomes", "good"),
    ("Medical research company secures top-tier grant", "good"),
    ("Pharma stock soars on positive drug trial results", "good"),
    ("Medical device company receives major industry award", "good"),
    ("Hospital chain reports robust financial performance", "good"),
    ("Insurance company expands into emerging markets", "good"),
    ("Pharmaceutical firm announces new drug pipeline", "good"),
    ("Biotech company secures patent for innovative treatment", "good"),
    ("Healthcare provider receives accreditation for quality care", "good"),
    ("Medical research company announces partnership with top researchers", "good"),
    ("Pharma company's stock climbs on strong sales report", "good"),
    ("Medical device firm launches innovative health product", "good"),
    ("Hospital chain sees increase in revenue", "good"),
    ("Insurance company reports lower-than-expected claims costs", "good"),
    ("Pharmaceutical company pioneers new vaccine technology", "good"),
    ("Biotech firm wins major research grant", "good"),
    ("Healthcare provider expands services to rural areas", "good"),
    ("Medical research company secures strategic partnerships", "good"),
    ("Pharma stock rises on positive quarterly results", "good"),
    ("Medical device company receives global recognition", "good"),
    ("Hospital chain reports increase in patient admissions", "good"),
    ("Insurance company introduces innovative healthcare plans", "good"),
    ("Pharmaceutical firm reports new drug success", "good"),
    ("Biotech company announces promising new research", "good"),
    ("Healthcare provider receives high patient satisfaction ratings", "good"),
    ("Medical research firm partners with international organizations", "good"),
    ("Pharma company's stock climbs after successful trial", "good"),
    ("Medical device company sees increased sales growth", "good"),
    ("Hospital chain reports strong financial health", "good"),
    ("Insurance company sees growth in premium revenue", "good"),
    ("Pharmaceutical company secures new international contract", "good"),
    ("Biotech firm announces breakthrough in treatment development", "good"),
    ("Healthcare provider reports increase in patient visits", "good"),
    ("Medical research company secures new funding", "good"),
    ("Pharma stock rises on strong financial performance", "good"),
    ("Medical device firm innovates with new health solutions", "good"),
    ("Hospital chain opens new medical center", "good"),
    ("Insurance company reports strong earnings growth", "good"),
    ("Pharmaceutical company pioneers new therapeutic approach", "good"),
    ("Biotech firm wins award for innovation", "good"),
    ("Healthcare provider expands into new geographical areas", "good"),
    ("Medical research company announces positive study results", "good"),
    ("Pharma company's stock soars on positive news", "good"),
    ("Medical device company launches new advanced product", "good"),
    ("Hospital chain reports growth in financial results", "good"),
    ("Insurance company sees high customer satisfaction", "good"),
    ("Pharmaceutical firm announces major breakthrough", "good"),
    ("Biotech company secures new research funding", "good"),
    ("Healthcare provider receives excellence award", "good"),
    ("Medical research firm partners with leading global institutions", "good"),
    ("Pharma stock rises on positive earnings report", "good"),
    ("Medical device company expands product portfolio", "good"),
    ("Hospital chain reports increased patient admissions", "good"),
    ("Insurance company announces new policy options", "good"),
    ("Pharmaceutical company secures major new patent", "good"),
    ("Biotech firm reports significant research progress", "good"),
    ("Healthcare provider sees strong financial performance", "good"),
    ("Medical research company secures significant new grant", "good"),
    ("Pharma stock climbs on positive clinical trial results", "good"),
    ("Medical device company receives prestigious industry award", "good"),
    ("Hospital chain reports record earnings", "good"),
    ("Insurance company expands into new service areas", "good"),
    ("Pharmaceutical firm reports new drug approval", "good"),
    ("Biotech company announces successful funding round", "good"),
    ("Healthcare provider receives top patient care ratings", "good"),
    ("Medical research company partners with leading hospitals", "good"),
    ("Pharma company's stock rises on strong market performance", "good"),
    ("Medical device firm launches cutting-edge technology", "good"),
    ("Hospital chain sees growth in patient numbers", "good"),
    ("Insurance company reports high revenue growth", "good"),
    ("Pharmaceutical company secures major research funding", "good"),
    ("Biotech firm announces breakthrough in clinical research", "good"),
    ("Healthcare provider reports strong patient outcomes", "good"),
    ("Medical research company secures top-tier investment", "good"),
    ("Pharma stock soars on positive market news", "good"),
    ("Medical device company receives international accreditation", "good"),
    ("Hospital chain reports financial growth", "good"),
    ("Insurance company introduces new customer-focused products", "good"),
    ("Pharmaceutical firm pioneers new medical technology", "good"),
    ("Biotech company secures patent for breakthrough treatment", "good"),
    ("Healthcare provider expands with new healthcare centers", "good"),
    ("Medical research company announces major scientific discovery", "good"),
    ("Pharma company's stock climbs on positive news", "good"),
    ("Medical device firm expands product range", "good"),
    ("Hospital chain sees increase in financial performance", "good"),
    ("Insurance company reports strong customer retention", "good"),
    ("Pharmaceutical company secures approval for innovative treatment", "good"),
    ("Biotech firm announces successful research outcomes", "good"),
    ("Healthcare provider reports high patient satisfaction", "good"),
    ("Medical research company partners with leading scientists", "good"),
    ("Pharma stock rises on strong sales data", "good"),
    ("Medical device company launches new innovative solution", "good"),
    ("Hospital chain opens new advanced care facility", "good"),
    ("Insurance company sees growth in premium income", "good"),
    ("Pharmaceutical firm announces major therapeutic breakthrough", "good"),
    ("Biotech company wins significant research grant", "good"),
    ("Healthcare provider expands services to underserved areas", "good"),
    ("Medical research company secures top-tier partnerships", "good"),
    ("Pharma stock climbs on positive earnings announcement", "good"),
    ("Medical device company receives global recognition for innovation", "good"),
    ("Hospital chain reports increase in patient volumes", "good"),
    ("Insurance company introduces new health coverage options", "good"),
    ("Pharmaceutical company secures major international contract", "good"),
    ("Biotech firm reports progress in groundbreaking research", "good"),
    ("Healthcare provider sees strong growth in patient care", "good"),
    ("Medical research company discovers innovative treatment methods", "good"),
    ("Pharma company's stock rises on new product launch", "good"),
    ("Medical device firm expands into new markets", "good"),
    ("Hospital chain reports strong earnings performance", "good"),
    ("Insurance company sees high customer satisfaction ratings", "good"),
    ("Pharmaceutical firm reports new drug success story", "good"),
    ("Biotech company announces promising research developments", "good"),
    ("Healthcare provider receives award for excellence in patient care", "good"),
    ("Medical research firm partners with top global institutions", "good"),
    ("Pharma stock climbs on positive drug news", "good"),
    ("Medical device company launches innovative health solutions", "good"),
    ("Hospital chain sees increase in revenue growth", "good"),
    ("Insurance company reports lower-than-expected claim costs", "good"),
    ("Pharmaceutical company pioneers new vaccine technology", "good"),
    ("Biotech firm wins major research grant", "good"),
    ("Healthcare provider expands services to rural areas", "good"),
    ("Medical research company secures strategic partnerships", "good"),
    ("Pharma stock rises on positive quarterly results", "good"),
    ("Medical device company receives global recognition", "good"),
    ("Hospital chain reports increase in patient admissions", "good"),
    ("Insurance company introduces innovative healthcare plans", "good"),
    ("Pharmaceutical firm reports new drug success", "good"),
    ("Biotech company announces promising new research", "good"),
    ("Healthcare provider receives high patient satisfaction ratings", "good"),
    ("Medical research firm partners with international organizations", "good"),
    ("Pharma company's stock climbs after successful trial", "good"),
    ("Medical device company sees increased sales growth", "good"),
    ("Hospital chain reports strong financial health", "good"),
    ("Insurance company sees growth in premium revenue", "good"),
    ("Pharmaceutical company secures new international contract", "good"),
    ("Biotech firm announces breakthrough in treatment development", "good"),
    ("Healthcare provider reports increase in patient visits", "good"),
    ("Medical research company secures new funding", "good"),
    ("Pharma stock rises on strong financial performance", "good"),
    ("Medical device firm innovates with new health solutions", "good"),
    ("Hospital chain opens new medical center", "good"),
    ("Insurance company reports strong earnings growth", "good"),
    ("Pharmaceutical company pioneers new therapeutic approach", "good"),
    ("Biotech firm wins award for innovation", "good"),
    ("Healthcare provider expands into new geographical areas", "good"),
    ("Medical research company announces positive study results", "good"),
    ("Pharma company's stock soars on positive news", "good"),
    ("Medical device company launches new advanced product", "good"),
    ("Hospital chain reports growth in financial results", "good"),
    ("Insurance company sees high customer satisfaction", "good"),
    ("Pharmaceutical firm announces major breakthrough", "good"),
    ("Biotech company secures new research funding", "good"),
    ("Healthcare provider receives excellence award", "good"),
    ("Medical research firm partners with leading global institutions", "good"),
    ("Pharma stock rises on positive earnings report", "good"),
    ("Medical device company expands product portfolio", "good"),
    ("Hospital chain reports increased patient admissions", "good"),
    ("Insurance company announces new policy options", "good"),
    ("Pharmaceutical company secures major new patent", "good"),
    ("Biotech firm reports significant research progress", "good"),
    ("Healthcare provider sees strong financial performance", "good"),
    ("Medical research company secures significant new grant", "good"),
    ("Pharma stock climbs on positive clinical trial results", "good"),
    ("Medical device company receives prestigious industry award", "good"),
    ("Hospital chain reports record earnings", "good"),
    ("Insurance company expands into new service areas", "good"),
    ("Pharmaceutical firm reports new drug approval", "good"),
    ("Biotech company announces successful funding round", "good"),
    ("Healthcare provider receives top patient care ratings", "good"),
    ("Medical research company partners with leading hospitals", "good"),
    ("Pharma company's stock rises on strong market performance", "good"),
    ("Medical device firm launches cutting-edge technology", "good"),
    ("Hospital chain sees growth in patient numbers", "good"),
    ("Insurance company reports high revenue growth", "good"),
    ("Pharmaceutical company secures major research funding", "good"),
    ("Biotech firm announces breakthrough in clinical research", "good"),
    ("Healthcare provider reports strong patient outcomes", "good"),
    ("Medical research company secures top-tier investment", "good"),
    ("Pharma stock soars on positive market news", "good"),
    ("Medical device company receives international accreditation", "good"),
    ("Hospital chain reports financial growth", "good"),
    ("Insurance company introduces new customer-focused products", "good"),
    ("Pharmaceutical firm pioneers new medical technology", "good"),
    ("Biotech company secures patent for breakthrough treatment", "good"),
    ("Healthcare provider expands with new healthcare centers", "good"),
    ("Medical research company announces major scientific discovery", "good"),
    ("Pharma company's stock climbs on positive news", "good"),
    ("Medical device firm expands product range", "good"),
    ("Hospital chain sees increase in financial performance", "good"),
    ("Insurance company reports strong customer retention", "good"),
    ("Pharmaceutical company secures approval for innovative treatment", "good"),
    ("Biotech firm announces successful research outcomes", "good"),
    ("Healthcare provider reports high patient satisfaction", "good"),
    ("Medical research company partners with leading scientists", "good"),
    ("Pharma stock rises on strong sales data", "good"),
    ("Medical device company launches new innovative solution", "good"),
    ("Hospital chain opens new advanced care facility", "good"),
    ("Insurance company sees growth in premium income", "good"),
    ("Pharmaceutical firm announces major therapeutic breakthrough", "good"),
    ("Biotech company wins significant research grant", "good"),
    ("Healthcare provider expands services to underserved areas", "good"),
    ("Medical research company secures top-tier partnerships", "good"),
    ("Pharma stock climbs on positive earnings announcement", "good"),
    ("Medical device company receives global recognition for innovation", "good"),
    ("Hospital chain reports increase in patient volumes", "good"),
    ("Insurance company introduces new health coverage options", "good"),
    ("Pharmaceutical company secures major international contract", "good"),
    ("Biotech firm reports progress in groundbreaking research", "good"),
    ("Healthcare provider sees strong growth in patient care", "good"),
    ("Medical research company discovers innovative treatment methods", "good"),
    ("Pharma company's stock rises on new product launch", "good"),
    ("Medical device firm expands into new markets", "good"),
    ("Hospital chain reports strong earnings performance", "good"),
    ("Insurance company sees high customer satisfaction ratings", "good"),
    ("Pharmaceutical firm reports new drug success story", "good"),
    ("Biotech company announces promising research developments", "good"),
    ("Healthcare provider receives award for excellence in patient care", "good"),
    ("Medical research firm partners with top global institutions", "good"),
    ("Pharma stock climbs on positive drug news", "good"),
    ("Medical device company launches innovative health solutions", "good"),
    ("Hospital chain sees increase in revenue growth", "good"),
    ("Insurance company reports lower-than-expected claim costs", "good"),
    ("Pharmaceutical company pioneers new vaccine technology", "good"),
    ("Biotech firm wins major research grant", "good"),
    ("Healthcare provider expands services to rural areas", "good"),
    ("Medical research company secures strategic partnerships", "good"),
    ("Pharma stock rises on positive quarterly results", "good"),
    ("Medical device company receives global recognition", "good"),
    ("Hospital chain reports increase in patient admissions", "good"),
    ("Insurance company introduces innovative healthcare plans", "good"),
    ("Pharmaceutical firm reports new drug success", "good"),
    ("Biotech company announces promising new research", "good"),
    ("Healthcare provider receives high patient satisfaction ratings", "good"),
    ("Medical research firm partners with international organizations", "good"),
    ("Pharma company's stock climbs after successful trial", "good"),
    ("Medical device company sees increased sales growth", "good"),
    ("Hospital chain reports strong financial health", "good"),
    ("Insurance company sees growth in premium revenue", "good"),
    ("Pharmaceutical company secures new international contract", "good"),
    ("Biotech firm announces breakthrough in treatment development", "good"),
    ("Healthcare provider reports increase in patient visits", "good"),
    ("Medical research company secures new funding", "good"),
    ("Mining company reports significant drop in quarterly profits", "bad"),
    ("Mining company faces lawsuits over environmental violations", "bad"),
    ("Major mine accident leads to multiple fatalities", "bad"),
    ("Mining firm fined for unsafe working conditions", "bad"),
    ("Government revokes mining company's operating license", "bad"),
    ("Mining company reports massive decline in ore quality", "bad"),
    ("Mining firm's stock plummets after CEO resignation", "bad"),
    ("Mining company halts operations due to equipment failure", "bad"),
    ("Environmental activists block access to major mining site", "bad"),
    ("Mining company reports higher-than-expected production costs", "bad"),
    ("Mining firm embroiled in corruption scandal", "bad"),
    ("Severe weather conditions disrupt mining operations", "bad"),
    ("Mining company downgraded by leading financial analysts", "bad"),
    ("Mining firm's expansion plans rejected by local government", "bad"),
    ("Mining company reports significant increase in debt", "bad"),
    ("Protests erupt at mining site over labor disputes", "bad"),
    ("Mining firm faces massive tax bill after audit", "bad"),
    ("Mining company's stock tumbles on poor earnings report", "bad"),
    ("Mining firm sued for breaching environmental regulations", "bad"),
    ("Mining company reports drop in global commodity prices", "bad"),
    ("Mining firm struggles with declining ore reserves", "bad"),
    ("Mining company faces backlash over land disputes", "bad"),
    ("Mining firm's operations suspended due to regulatory issues", "bad"),
    ("Mining company reports major spill contaminating local water supply", "bad"),
    ("Mining firm's labor union threatens strike action", "bad"),
    ("Mining company fined for illegal mining activities", "bad"),
    ("Mining firm reports lower-than-expected production output", "bad"),
    ("Mining company faces class action lawsuit from local communities", "bad"),
    ("Mining firm's equipment damaged in severe storm", "bad"),
    ("Mining company reports significant increase in operational costs", "bad"),
    ("Mining firm downgraded by credit rating agencies", "bad"),
    ("Mining company halts project amid financial difficulties", "bad"),
    ("Mining firm faces allegations of worker exploitation", "bad"),
    ("Mining company's stock plunges on negative market outlook", "bad"),
    ("Mining firm reports delays in new project development", "bad"),
    ("Mining company faces major lawsuit over toxic waste dumping", "bad"),
    ("Mining firm's permit application rejected by government", "bad"),
    ("Mining company reports lower-than-expected revenue", "bad"),
    ("Mining firm's CEO under investigation for fraud", "bad"),
    ("Mining company suspends dividends amid financial strain", "bad"),
    ("Mining firm faces public outcry over environmental impact", "bad"),
    ("Mining company's stock falls on news of operational disruptions", "bad"),
    ("Mining firm reports significant decrease in mineral prices", "bad"),
    ("Mining company faces international sanctions", "bad"),
    ("Mining firm accused of bribery in foreign operations", "bad"),
    ("Mining company reports major infrastructure damage", "bad"),
    ("Mining firm's workers go on strike over wage disputes", "bad"),
    ("Mining company faces backlash over cultural heritage site destruction", "bad"),
    ("Mining firm's expansion halted due to environmental concerns", "bad"),
    ("Mining company reports financial losses in latest quarter", "bad"),
    ("Mining firm embroiled in legal battle over land rights", "bad"),
    ("Mining company's stock dips on disappointing production forecast", "bad"),
    ("Mining firm fined for air pollution violations", "bad"),
    ("Mining company reports significant increase in employee injuries", "bad"),
    ("Mining firm faces community backlash over health concerns", "bad"),
    ("Mining company sees decline in investor confidence", "bad"),
    ("Mining firm reports delays in key project milestones", "bad"),
    ("Mining company faces backlash over deforestation activities", "bad"),
    ("Mining firm's operations disrupted by local protests", "bad"),
    ("Mining company reports lower-than-expected cash flow", "bad"),
    ("Mining firm fined for failing safety inspections", "bad"),
    ("Mining company's stock drops on poor financial outlook", "bad"),
    ("Mining firm accused of human rights violations", "bad"),
    ("Mining company reports significant cost overruns", "bad"),
    ("Mining firm's project approval delayed by regulatory agencies", "bad"),
    ("Mining company faces severe criticism over water usage", "bad"),
    ("Mining firm's operations affected by geopolitical tensions", "bad"),
    ("Mining company reports lower mineral extraction rates", "bad"),
    ("Mining firm faces massive cleanup costs after environmental damage", "bad"),
    ("Mining company's stock falls on news of management shake-up", "bad"),
    ("Mining firm reports higher-than-expected operational losses", "bad"),
    ("Mining company faces protests over land acquisition", "bad"),
    ("Mining firm's new project faces regulatory hurdles", "bad"),
    ("Mining company reports lower commodity prices impacting revenue", "bad"),
    ("Mining firm's operations disrupted by natural disasters", "bad"),
    ("Mining company faces backlash over community displacement", "bad"),
    ("Mining firm reports significant increase in legal expenses", "bad"),
    ("Mining company's stock tumbles on market speculation", "bad"),
    ("Mining firm fined for violating safety protocols", "bad"),
    ("Mining company reports lower production due to equipment failures", "bad"),
    ("Mining firm faces allegations of illegal mining practices", "bad"),
    ("Mining company's stock falls on negative analyst reports", "bad"),
    ("Mining firm reports decline in ore grades", "bad"),
    ("Mining company faces public opposition to new project", "bad"),
    ("Mining firm's operations halted due to labor strikes", "bad"),
    ("Mining company reports major decrease in net profit", "bad"),
    ("Mining firm faces scrutiny over tax evasion allegations", "bad"),
    ("Mining company's stock plummets on poor earnings forecast", "bad"),
    ("Mining firm fined for breaching environmental laws", "bad"),
    ("Mining company reports delays in production ramp-up", "bad"),
    ("Mining firm faces backlash over mine expansion plans", "bad"),
    ("Mining company's stock declines on negative market sentiment", "bad"),
    ("Mining firm reports significant increase in operating losses", "bad"),
    ("Mining company faces legal action over contamination claims", "bad"),
    ("Mining firm's operations affected by supply chain disruptions", "bad"),
    ("Mining company reports lower-than-expected production yields", "bad"),
    ("Mining firm fined for failing to meet regulatory standards", "bad"),
    ("Mining company's stock drops on weak financial results", "bad"),
    ("Mining firm faces community protests over environmental degradation", "bad"),
    ("Mining company reports significant increase in maintenance costs", "bad"),
    ("Mining firm's expansion plans face local opposition", "bad"),
    ("Mining company reports decline in ore extraction efficiency", "bad"),
    ("Mining company reports record quarterly profits", "good"),
    ("Mining firm discovers significant new ore deposit", "good"),
    ("Mining company receives government approval for new project", "good"),
    ("Mining firm reduces operational costs through new technology", "good"),
    ("Mining company's stock surges on positive earnings report", "good"),
    ("Mining firm wins prestigious industry award", "good"),
    ("Mining company secures major new contract", "good"),
    ("Mining firm reports increase in ore quality", "good"),
    ("Mining company expands operations to new region", "good"),
    ("Mining firm receives environmental certification", "good"),
    ("Mining company's stock rises on strong market performance", "good"),
    ("Mining firm successfully completes major project ahead of schedule", "good"),
    ("Mining company announces major investment in sustainable practices", "good"),
    ("Mining firm's expansion plans approved by local authorities", "good"),
    ("Mining company reports decrease in production costs", "good"),
    ("Mining firm sees increased demand for its minerals", "good"),
    ("Mining company secures significant financing for expansion", "good"),
    ("Mining firm's stock climbs on positive industry outlook", "good"),
    ("Mining company partners with leading technology provider", "good"),
    ("Mining firm reports increased production output", "good"),
    ("Mining company's safety initiatives lead to lower accident rates", "good"),
    ("Mining firm receives community support for new project", "good"),
    ("Mining company reports strong cash flow", "good"),
    ("Mining firm achieves high marks in corporate social responsibility", "good"),
    ("Mining company's stock rises on news of new discovery", "good"),
    ("Mining firm secures favorable terms in new labor agreement", "good"),
    ("Mining company reports increased efficiency through automation", "good"),
    ("Mining firm's innovative practices reduce environmental impact", "good"),
    ("Mining company announces major new mineral find", "good"),
    ("Mining firm reports strong financial health", "good"),
    ("Mining company secures new export deal", "good"),
    ("Mining firm's community engagement initiatives praised", "good"),
    ("Mining company reports lower-than-expected debt levels", "good"),
    ("Mining firm expands into new international markets", "good"),
    ("Mining company's stock rises on positive economic indicators", "good"),
    ("Mining firm secures new strategic partnerships", "good"),
    ("Mining company reports increase in shareholder value", "good"),
    ("Mining firm's innovative technology boosts production", "good"),
    ("Mining company receives recognition for sustainability efforts", "good"),
    ("Mining firm's workforce praised for efficiency and safety", "good"),
    ("Mining company reports significant increase in mineral prices", "good"),
    ("Mining firm's stock climbs on news of acquisition", "good"),
    ("Mining company announces major investment in clean energy", "good"),
    ("Mining firm reports high employee satisfaction rates", "good"),
    ("Mining company's exploration efforts yield positive results", "good"),
    ("Mining firm's community programs recognized for excellence", "good"),
    ("Mining company reports increase in net income", "good"),
    ("Mining firm's stock rises on positive quarterly results", "good"),
    ("Mining company announces new green mining initiative", "good"),
    ("Mining firm secures funding for major new project", "good"),
    ("Mining company reports strong demand for its products", "good"),
    ("Mining firm's safety record improves significantly", "good"),
    ("Mining company receives award for best practices", "good"),
    ("Mining firm's stock climbs on positive market trends", "good"),
    ("Mining company announces new cost-saving measures", "good"),
    ("Mining firm's innovation leads to higher productivity", "good"),
    ("Mining company reports increase in operational efficiency", "good"),
    ("Mining firm's community partnerships praised by local leaders", "good"),
    ("Mining company secures long-term supply agreement", "good"),
    ("Mining firm's stock rises on favorable industry news", "good"),
    ("Mining company reports reduction in environmental impact", "good"),
    ("Mining firm's new technology enhances ore recovery", "good"),
    ("Mining company receives high environmental standards certification", "good"),
    ("Mining firm's workforce benefits from new training programs", "good"),
    ("Mining company's stock rises on strong annual performance", "good"),
    ("Mining firm secures major new investment", "good"),
    ("Mining company reports increase in mineral reserves", "good"),
    ("Mining firm's community outreach programs gain recognition", "good"),
    ("Mining company announces major new exploration project", "good"),
    ("Mining firm's stock climbs on positive financial forecast", "good"),
    ("Mining company receives award for innovation in mining", "good"),
    ("Mining firm's environmental initiatives reduce carbon footprint", "good"),
    ("Mining company reports record production levels", "good"),
    ("Mining firm's partnership with local communities strengthens", "good"),
    ("Mining company reports significant cost savings", "good"),
    ("Mining firm's stock rises on news of strategic merger", "good"),
    ("Mining company receives top safety rating", "good"),
    ("Mining firm's expansion into new areas boosts revenue", "good"),
    ("Mining company reports positive results from pilot project", "good"),
    ("Mining firm's innovative methods improve resource management", "good"),
    ("Mining company secures key regulatory approvals", "good"),
    ("Mining firm's stock climbs on positive exploration results", "good"),
    ("Mining company announces new sustainable mining practices", "good"),
    ("Mining firm's employees recognized for outstanding performance", "good"),
    ("Mining company reports increase in global demand", "good"),
    ("Mining firm's stock rises on favorable commodity prices", "good"),
    ("Mining company receives award for corporate responsibility", "good"),
    ("Mining firm's technological advancements increase efficiency", "good"),
    ("Mining company reports strong revenue growth", "good"),
    ("Mining firm's safety measures lead to zero accidents", "good"),
    ("Mining company announces major new sustainability initiative", "good"),
    ("Mining firm's stock climbs on positive industry trends", "good"),
    ("Mining company reports lower production costs", "good"),
    ("Mining firm's partnerships enhance community development", "good"),
    ("Mining company secures new supply chain agreements", "good"),
    ("Mining firm's stock rises on positive quarterly earnings", "good"),
    ("Mining company receives high marks for environmental stewardship", "good"),
    ("Mining firm's innovative solutions reduce operational costs", "good"),
    ("Mining company reports increase in shareholder returns", "good"),
    ("Mining firm's stock climbs on news of successful expansion", "good"),
    ("Mining company receives recognition for best industry practices", "good"),
    ("Mining firm's new initiatives support local economies", "good"),
    ("Mining company reports positive outcomes from new projects", "good"),
    ("Mining firm's stock rises on strong commodity prices", "good"),
    ("Mining company announces new advancements in mining technology", "good"),
    ("Mining firm's sustainability efforts yield positive results", "good"),
    ("Mining company reports high profitability", "good"),
    ("Company announces upcoming shareholder meeting", "neutral"),
    ("Company releases quarterly earnings report", "neutral"),
    ("Company plans to restructure management team", "neutral"),
    ("Company schedules annual general meeting", "neutral"),
    ("Company updates guidance for next fiscal year", "neutral"),
    ("Company completes routine maintenance at facility", "neutral"),
    ("Company appoints new board member", "neutral"),
    ("Company provides mid-year performance update", "neutral"),
    ("Company issues press release on operational changes", "neutral"),
    ("Company finalizes routine financial audit", "neutral"),
    ("Company releases new product specifications", "neutral"),
    ("Company announces changes to dividend policy", "neutral"),
    ("Company outlines strategic goals for next quarter", "neutral"),
    ("Company reports on industry conference participation", "neutral"),
    ("Company issues statement on regulatory compliance", "neutral"),
    ("Company updates investor relations website", "neutral"),
    ("Company details progress on ongoing projects", "neutral"),
    ("Company responds to media inquiries", "neutral"),
    ("Company announces minor changes to bylaws", "neutral"),
    ("Company provides update on legal proceedings", "neutral"),
    ("Company releases sustainability report", "neutral"),
    ("Company updates on international market activities", "neutral"),
    ("Company announces minor operational adjustments", "neutral"),
    ("Company reports on community engagement efforts", "neutral"),
    ("Company provides update on corporate social responsibility initiatives", "neutral"),
    ("Company announces routine financial results", "neutral"),
    ("Company details plans for upcoming quarter", "neutral"),
    ("Company releases technical report on new project", "neutral"),
    ("Company updates on partnership activities", "neutral"),
    ("Company responds to industry developments", "neutral"),
    ("Company outlines changes to executive compensation", "neutral"),
    ("Company issues update on infrastructure improvements", "neutral"),
    ("Company reports on employee training programs", "neutral"),
    ("Company announces updates to internal policies", "neutral"),
    ("Company releases information on research and development efforts", "neutral"),
    ("Company details performance metrics for past year", "neutral"),
    ("Company provides update on supply chain activities", "neutral"),
    ("Company announces minor changes to operational processes", "neutral"),
    ("Company reports on market conditions", "neutral"),
    ("Company outlines plans for new fiscal year", "neutral"),
    ("Company releases information on industry partnerships", "neutral"),
    ("Company provides update on customer service initiatives", "neutral"),
    ("Company reports on minor product adjustments", "neutral"),
    ("Company announces new corporate governance policies", "neutral"),
    ("Company details progress on technological advancements", "neutral"),
    ("Company provides update on product testing", "neutral"),
    ("Company releases information on marketing activities", "neutral"),
    ("Company announces routine updates to software", "neutral"),
    ("Company reports on internal restructuring", "neutral"),
    ("Company details updates to manufacturing processes", "neutral"),
    ("Company provides update on quality control measures", "neutral"),
    ("Company releases information on environmental impact studies", "neutral"),
    ("Company announces new training programs for staff", "neutral"),
    ("Company reports on internal audits", "neutral"),
    ("Company details plans for minor infrastructure upgrades", "neutral"),
    ("Company provides update on stakeholder engagement", "neutral"),
    ("Company releases information on industry standards compliance", "neutral"),
    ("Company announces minor changes to distribution network", "neutral"),
    ("Company reports on facility maintenance activities", "neutral"),
    ("Company details new health and safety measures", "neutral"),
    ("Company provides update on data security efforts", "neutral"),
    ("Company releases information on minor product recalls", "neutral"),
    ("Company announces updates to marketing strategy", "neutral"),
    ("Company reports on customer feedback", "neutral"),
    ("Company details minor operational improvements", "neutral"),
    ("Company provides update on financial planning", "neutral"),
    ("Company releases information on stakeholder meetings", "neutral"),
    ("Company announces routine upgrades to equipment", "neutral"),
    ("Company reports on minor supply chain disruptions", "neutral"),
    ("Company details progress on compliance initiatives", "neutral"),
    ("Company provides update on intellectual property filings", "neutral"),
    ("Company releases information on strategic alliances", "neutral"),
    ("Company announces updates to employee benefits", "neutral"),
    ("Company reports on market analysis", "neutral"),
    ("Company details new data management practices", "neutral"),
    ("Company provides update on regional activities", "neutral"),
    ("Company releases information on industry awards", "neutral"),
    ("Company announces routine updates to corporate policies", "neutral"),
    ("Company reports on minor operational setbacks", "neutral"),
    ("Company details progress on innovation initiatives", "neutral"),
    ("Company provides update on brand development", "neutral"),
    ("Company releases information on stakeholder feedback", "neutral"),
    ("Company announces updates to production schedules", "neutral"),
    ("Company reports on customer satisfaction surveys", "neutral"),
    ("Company details new sustainability initiatives", "neutral"),
    ("Company provides update on facility expansions", "neutral"),
    ("Company releases information on industry research", "neutral"),
    ("Company announces routine updates to investor presentations", "neutral"),
    ("Company reports on minor product modifications", "neutral"),
    ("Company details progress on strategic projects", "neutral"),
    ("Company provides update on digital transformation efforts", "neutral"),
    ("Company releases information on supplier relationships", "neutral"),
    ("Company announces updates to corporate communications", "neutral"),
    ("Company reports on employee engagement activities", "neutral"),
    ("Company details new operational guidelines", "neutral"),
    ("Company provides update on market entry strategies", "neutral"),
    ("Company releases information on financial compliance", "neutral"),
    ("Company announces routine updates to HR policies", "neutral"),
    ("Company reports on minor technological upgrades", "neutral"),
    ("Company details progress on capital projects", "neutral"),
    ("Company provides update on strategic objectives", "neutral"),
    ("Company releases information on regulatory filings", "neutral"),
    ("Company announces updates to procurement processes", "neutral"),
    ("Company reports on minor organizational changes", "neutral"),
    ("Company details new customer engagement initiatives", "neutral"),
    ("Company provides update on market expansion plans", "neutral"),
    ("Company releases information on financial audits", "neutral"),
    ("Company announces routine updates to safety protocols", "neutral"),
    ("Company reports on minor production issues", "neutral"),
    ("Company details progress on operational efficiencies", "neutral"),
    ("Company provides update on community relations", "neutral"),
    ("Company releases information on industry benchmarks", "neutral"),
    ("Company announces updates to internal controls", "neutral"),
    ("Company reports on minor staffing changes", "neutral"),
    ("Company details new strategic partnerships", "neutral"),
    ("Company provides update on research partnerships", "neutral"),
    ("Company releases information on corporate events", "neutral"),
    ("Company announces routine updates to technology platforms", "neutral"),
    ("Company reports on minor inventory adjustments", "neutral"),
    ("Company details progress on workforce development", "neutral"),
    ("New environmental regulations increase operational costs for companies", "bad"),
    ("Government imposes higher taxes on corporate profits", "bad"),
    ("Major protest movements disrupt business activities", "bad"),
    ("New labor laws increase minimum wage and operational expenses", "bad"),
    ("Public backlash against major corporation leads to boycott", "bad"),
    ("Rise in trade tensions results in higher tariffs on goods", "bad"),
    ("New health regulations require costly compliance measures", "bad"),
    ("Consumer preference shifts away from company's core products", "bad"),
    ("Increase in cyberattacks prompts higher security spending", "bad"),
    ("Government enacts stricter emissions standards", "bad"),
    ("Economic downturn reduces consumer spending", "bad"),
    ("New data privacy laws increase compliance costs", "bad"),
    ("Public outcry over company practices leads to regulatory scrutiny", "bad"),
    ("Inflation leads to higher costs for raw materials", "bad"),
    ("Changes in foreign policy impact international trade agreements", "bad"),
    ("Rise in energy costs increases production expenses", "bad"),
    ("Pandemic resurgence leads to renewed restrictions and closures", "bad"),
    ("Government announces new financial regulations affecting businesses", "bad"),
    ("Public health crisis impacts workforce availability", "bad"),
    ("Major lawsuit against corporation for environmental damage", "bad"),
    ("Consumer confidence declines due to economic uncertainty", "bad"),
    ("New import restrictions disrupt supply chains", "bad"),
    ("Government increases corporate tax rates", "bad"),
    ("Public protests against corporate policies lead to image crisis", "bad"),
    ("Natural disaster disrupts production and distribution", "bad"),
    ("Global recession impacts sales and revenue", "bad"),
    ("Government mandates higher spending on employee benefits", "bad"),
    ("Major cyber breach exposes company vulnerabilities", "bad"),
    ("Public awareness campaigns lead to reduced demand for certain products", "bad"),
    ("Changes in trade policies lead to increased costs", "bad"),
    ("Government imposes stricter safety regulations", "bad"),
    ("Economic sanctions affect company's overseas operations", "bad"),
    ("Health scares related to product lead to consumer distrust", "bad"),
    ("Rising interest rates increase borrowing costs", "bad"),
    ("Public backlash against executive compensation practices", "bad"),
    ("New environmental impact assessments delay projects", "bad"),
    ("Increased competition in the market affects profitability", "bad"),
    ("Public demand for transparency leads to higher compliance costs", "bad"),
    ("Changes in labor laws require extensive operational adjustments", "bad"),
    ("Government enacts new tariffs impacting import costs", "bad"),
    ("Public criticism over ethical concerns leads to brand damage", "bad"),
    ("New consumer protection laws increase regulatory requirements", "bad"),
    ("Public health regulations require costly adaptations", "bad"),
    ("Economic instability affects investment and growth", "bad"),
    ("Public outcry over product safety leads to recalls", "bad"),
    ("New corporate governance laws increase compliance burdens", "bad"),
    ("Public backlash against environmental practices impacts sales", "bad"),
    ("Government imposes new taxes on specific industries", "bad"),
    ("Major shift in consumer behavior reduces demand", "bad"),
    ("Changes in financial reporting standards increase operational complexity", "bad"),
    ("Economic crisis leads to widespread market volatility", "bad"),
    ("Government reduces corporate tax rates", "good"),
    ("New trade agreement opens up international markets", "good"),
    ("Technological advancements improve operational efficiency", "good"),
    ("Government introduces subsidies for green energy projects", "good"),
    ("Consumer confidence increases amid economic growth", "good"),
    ("Public support grows for company's environmental initiatives", "good"),
    ("New labor laws streamline hiring processes", "good"),
    ("Healthcare reform reduces employer healthcare costs", "good"),
    ("Government invests in infrastructure development", "good"),
    ("Public awareness of healthy lifestyles boosts demand for company's products", "good"),
    ("New data privacy laws encourage consumer trust", "good"),
    ("Rise in disposable income increases consumer spending", "good"),
    ("Government provides grants for technological innovation", "good"),
    ("Improved trade relations reduce import/export costs", "good"),
    ("Public demand for sustainable products increases sales", "good"),
    ("New financial regulations encourage investment", "good"),
    ("Advances in automation reduce production costs", "good"),
    ("Government reduces environmental regulations", "good"),
    ("Rise in stock market boosts investor confidence", "good"),
    ("New policies support small business growth", "good"),
    ("Public interest in renewable energy supports industry growth", "good"),
    ("Government provides tax incentives for research and development", "good"),
    ("Economic recovery boosts consumer demand", "good"),
    ("Public support for local businesses drives sales growth", "good"),
    ("New trade policies favor domestic industries", "good"),
    ("Government invests in education and workforce training", "good"),
    ("Public appreciation for company values boosts brand loyalty", "good"),
    ("Advances in healthcare technology open new markets", "good"),
    ("Government offers low-interest loans for business expansion", "good"),
    ("Public initiatives for clean energy support industry leaders", "good"),
    ("New consumer protection laws increase market stability", "good"),
    ("Rise in global middle class boosts market potential", "good"),
    ("Government reduces tariffs on essential goods", "good"),
    ("Public shift towards digital services supports tech industry", "good"),
    ("Economic stimulus packages increase consumer spending", "good"),
    ("Government support for innovation drives industry growth", "good"),
    ("Public focus on environmental sustainability drives sales", "good"),
    ("Advances in logistics improve supply chain efficiency", "good"),
    ("Government reduces regulations on financial markets", "good"),
    ("Public demand for ethical products boosts sales", "good"),
    ("Economic growth in emerging markets opens new opportunities", "good"),
    ("Government incentives for renewable energy projects", "good"),
    ("Public trust in financial markets increases investment", "good"),
    ("Rise in online shopping boosts e-commerce sector", "good"),
    ("Government support for export industries drives growth", "good"),
    ("Public interest in tech innovation supports startup growth", "good"),
    ("Economic policies favoring business development", "good"),
    ("Public focus on health and wellness boosts related industries", "good"),
    ("Advances in biotechnology open new market opportunities", "good"),
    ("Government funding for infrastructure projects boosts economy", "good"),
    ("Public initiatives for recycling support sustainable companies", "good"),
    ("Economic stability increases investor confidence", "good"),
    ("Tech giant announces groundbreaking new product -- But will it live up to the hype?", "good"),
    ("Company reports record-breaking profits -- But can they sustain the momentum?", "good"),
    ("Global trade tensions ease -- Or do they?", "neutral"),
    ("Stock market rallies to new highs -- But is it too good to last?", "good"),
    ("Economic recovery in sight -- But will inflation derail it?", "neutral"),
    ("Company announces major expansion plans -- But are they overextending?", "good"),
    ("Government unveils ambitious infrastructure projects -- But can they deliver?", "neutral"),
    ("Consumer spending reaches all-time high -- But is it sustainable?", "good"),
    ("Renewable energy sector booms -- But is it a bubble?", "good"),
    ("E-commerce sales surge -- But is brick-and-mortar retail dying?", "neutral"),
    ("Major tech company faces antitrust scrutiny -- But will regulators take action?", "bad"),
    ("Automotive industry embraces electric vehicles -- But is the infrastructure ready?", "good"),
    ("Interest rates remain stable -- But will they rise soon?", "neutral"),
    ("Healthcare sector sees innovation boom -- But are costs still too high?", "good"),
    ("New environmental regulations proposed -- But will they hurt businesses?", "bad"),
    ("Cryptocurrency market sees volatility -- But is it here to stay?", "neutral"),
    ("Travel industry rebounds -- But will new variants halt the recovery?", "good"),
    ("Global supply chain disruptions continue -- But when will they ease?", "bad"),
    ("Company faces backlash over labor practices -- But will consumers boycott?", "bad"),
    ("Home prices soar -- But is it a housing bubble?", "neutral"),
    ("Fintech startups disrupt traditional banking -- But can they survive regulation?", "good"),
    ("Artificial intelligence revolutionizes industries -- But at what cost to jobs?", "neutral"),
    ("Gig economy thrives -- But are workers being exploited?", "neutral"),
    ("Renewed interest in space exploration -- But who will foot the bill?", "neutral"),
    ("Social media platform under fire for privacy violations -- But will users abandon it?", "bad"),
    ("Food delivery services see surge in demand -- But can they turn a profit?", "neutral"),
    ("Fashion industry embraces sustainability -- But is it just greenwashing?", "neutral"),
    ("Cybersecurity threats on the rise -- But are companies prepared?", "bad"),
    ("Biotech company makes breakthrough in cancer treatment -- But is it too good to be true?", "good"),
    ("Retailers experiment with augmented reality shopping -- But will it catch on?", "neutral"),
    ("Rise of remote work culture -- But are employees feeling isolated?", "neutral"),
    ("Renewable energy subsidies extended -- But will they be enough?", "good"),
    ("Global pandemic accelerates digital transformation -- But what about digital divide?", "neutral"),
    ("Automotive industry shifts towards autonomous vehicles -- But are they safe?", "neutral"),
    ("Streaming services dominate entertainment industry -- But is quality suffering?", "neutral"),
    ("Corporate giants face pressure to address climate change -- But are they sincere?", "neutral"),
    ("Economic stimulus package passed -- But will it lead to inflation?", "neutral"),
    ("Medical breakthrough promises cure for rare disease -- But will it be affordable?", "good"),
    ("Education sector adopts online learning -- But what about access for all?", "neutral"),
    ("Social media influencers reshape marketing landscape -- But are they trustworthy?", "neutral"),
    ("Retailers struggle with supply chain disruptions -- But is it temporary?", "bad"),
    ("Telemedicine gains popularity -- But what about doctor-patient relationship?", "neutral"),
    ("Food delivery apps accused of exploiting workers -- But are they essential?", "bad"),
    ("Renewable energy sector sees investment boom -- But is it a bubble?", "good"),
    ("Artificial intelligence enhances customer service -- But what about privacy?", "neutral"),
    ("Real estate market faces uncertainty -- But are there bargains to be had?", "neutral"),
    ("Online gaming industry sees exponential growth -- But what about addiction?", "neutral"),
    ("Remote work becomes permanent for many companies -- But what about office culture?", "neutral"),
    ("Telecommunications companies roll out 5G networks -- But are health concerns valid?", "neutral"),
    ("Renewable energy outpaces fossil fuels in new investments -- But will government subsidies last?", "good"),
    ("Tech sector grapples with ethical implications of AI -- But who decides?", "neutral"),
    ("Shift towards plant-based diets -- But what about impact on agriculture?", "neutral"),
    ("Renewed interest in outdoor recreation -- But what about environmental impact?", "neutral"),
    ("Green bonds gain popularity in finance sector -- But are they just a fad?", "good"),
    ("Fashion industry embraces inclusivity -- But what about cultural appropriation?", "neutral"),
    ("Rise of remote healthcare services -- But what about access for underserved communities?", "neutral"),
    ("Renewable energy overtakes coal in power generation -- But what about grid stability?", "good"),
    ("Global pandemic accelerates shift towards online shopping -- But what about local businesses?", "neutral"),
    ("Artificial intelligence improves efficiency in healthcare -- But what about patient privacy?", "neutral"),
    ("Economic recovery leads to surge in job creation -- But what about wage inequality?", "neutral")
]